export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    SUB_QUANTITY: 'SUB_QUANTITY',
    ADD_QUANTITY: 'ADD_QUANTITY',
    ADD_SHIPPING: 'ADD_SHIPPING',
    PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
    PRODUCT_FAILURE: 'PRODUCT_FAILURE',
    PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
    PRODUCT_DETAIL_FAILURE: 'PRODUCT_DETAIL_FAILURE',
    PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
    EMPTY_CART:'EMPTY_CART',
    ORDER_DATA:'ORDER_DATA'
};

export default userConstants;
